//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BromoAirlineDesktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akun
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string nama { get; set; }
        public System.DateTime tanggalLahir { get; set; }
        public string nomorTelepon { get; set; }
        public bool merupakanAdmin { get; set; }
    }
}
