//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BromoAirlineDesktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JadwalPenerbangan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JadwalPenerbangan()
        {
            this.PerubahanStatusJadwalPenerbangans = new HashSet<PerubahanStatusJadwalPenerbangan>();
            this.TransaksiHeaders = new HashSet<TransaksiHeader>();
        }
    
        public int id { get; set; }
        public string kodePenerbangan { get; set; }
        public int bandaraKeberangkatanID { get; set; }
        public int bandaraTujuanID { get; set; }
        public int maskapaiID { get; set; }
        public System.DateTime tanggalWaktuKeberangkatan { get; set; }
        public int durasiPenerbangan { get; set; }
        public double hargaPerTiket { get; set; }
    
        public virtual Bandara Bandara { get; set; }
        public virtual Bandara Bandara1 { get; set; }
        public virtual Maskapai Maskapai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerubahanStatusJadwalPenerbangan> PerubahanStatusJadwalPenerbangans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaksiHeader> TransaksiHeaders { get; set; }
    }
}
