//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BromoAirlineDesktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KodePromo
    {
        public int id { get; set; }
        public string kode { get; set; }
        public double presentaseDiskon { get; set; }
        public double maksimumDiskon { get; set; }
        public System.DateTime berlakuSampai { get; set; }
        public string deskripsi { get; set; }
    }
}
