//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BromoAirlineDesktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaksiDetail
    {
        public int id { get; set; }
        public int transaksiHeaderID { get; set; }
        public string titelPenumpang { get; set; }
        public string namaLengkapPenumpang { get; set; }
    
        public virtual TransaksiHeader TransaksiHeader { get; set; }
    }
}
